"""Public interface for the ROI-H installer."""

from roi_h_installer.core import InstallerError, apply, inspect, plan
from roi_h_installer.models import (
    DataCompatibility,
    DataState,
    EffectKind,
    ErrorCategory,
    InstallationState,
    InstallerErrorCode,
    InstallerFailure,
    InstallOperation,
    InstallPlan,
    InstallRequest,
    InstallResult,
    PlanEffect,
    PlanRequirement,
    PointerState,
    RecoveryStep,
    RequirementKind,
    StagingState,
    TrustedRelease,
    TrustedTarget,
)

__all__ = [
    "DataCompatibility",
    "DataState",
    "EffectKind",
    "ErrorCategory",
    "InstallOperation",
    "InstallPlan",
    "InstallRequest",
    "InstallResult",
    "InstallationState",
    "InstallerError",
    "InstallerErrorCode",
    "InstallerFailure",
    "PlanEffect",
    "PlanRequirement",
    "PointerState",
    "RecoveryStep",
    "RequirementKind",
    "StagingState",
    "TrustedRelease",
    "TrustedTarget",
    "apply",
    "inspect",
    "plan",
]
